### ISSUE TITLE
Thoughts on Recent Changes

### ISSUE THREAD

**Issue by rmorshea** [jimbaker/tagstr#27]
- Update `conv` type to be a `Literal`
- `raw` should be `text`
- `cooked` maybe doesn't really describe what's going on without explanation
- explain why we call it a Thunk - a piece of code that does some delayed work ([source](https://redux.js.org/usage/writing-logic-thunks#:~:text=What%20is%20a%20%22thunk%22%3F,to%20perform%20the%20work%20later.)).

**Comment by pauleveritt** [comment]
@jimbaker I believe some of this is covered now in latest updates. Any action left?
