### ISSUE TITLE
Convert docs from rst to md?

### ISSUE THREAD

**Issue by pauleveritt** [jimbaker/tagstr#33]
I wanted the docs top page to share the content from the README. But it's `README.md` not `README.rst`.

I propose switching to MyST and Markdown for the stuff in docs. Obviously the PEP would remain in RST, but MyST supports RST/MD mixing.

**Comment by merwok** [comment]
The readme is short, github supports rendering reST, what about converting to README.rst?

**Comment by pauleveritt** [comment]
As mentioned in #40 we are stripping down this repo. The tutorial is being worked on as part of a "site"  that is on a different timing than the PEP, so closing this.
